version: '3.7'

services:
  main:
    container_name: ta_main
    build:
      context: .
      target: development
    command: npm run start:dev
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - "9229:9229"
    entrypoint: ["npm", "run", "start:${NODE_ENV}"]
    env_file:
      - .env
    networks:
      - ta_net
    restart: unless-stopped

  postgres:
    container_name: ta_postgres
    image: postgres:12
    restart: always
    networks:
      - ta_net
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ta_pgadmin
    restart: always
    networks:
      - ta_net
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  ta_net:
volumes:
  pgdata:
  pgadmin-data: