version: '3.7'

services:
  main:
    container_name: ta_cards_main
    build:
      context: .
      target: development
    command: npm run start:dev
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - "9229:9229"
    entrypoint: ["npm", "run", "start:${NODE_ENV}"]
    env_file:
      - .env
    networks:
      - games_net
    restart: unless-stopped

  redis:
    image: redis
    container_name: ta_cards_redis
    networks:
      - games_net
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    entrypoint: redis-server --appendonly yes
    restart: always

  postgres:
    container_name: ta_cards_postgres
    image: postgres:12
    restart: always
    networks:
      - games_net
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  games_net:
volumes:
  pgdata:
  redis-data: