
version: '3.1'

services:

  db_postgres:
    image: postgres:12
    restart: always
    volumes:
      - data-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports: 
      - "5432:5432"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    entrypoint: redis-server --appendonly yes
    restart: always

volumes:
  data-volume:
  redis-data:
  mongodb-data: