
version: '3.1'

services:

  db_postgres:
    image: postgres:12
    restart: always
    volumes:
      - data-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports: 
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    entrypoint: redis-server --appendonly yes
    restart: always

volumes:
  data-volume:
  redis-data: